openapi: "3.0.3"

info:
  title: "Zephyr API"
  description: "This API allows authenticated users to create, edit, and manage journals"
  version: "0.0.1"

servers:
  - url: "http://0.0.0.0:8080"
    description: Development Server

paths:
  # AUTH PATHS
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Endpoint allowing users to register for Zephyr
      requestBody:
        description: Information used to create new user entity
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        201:
          description: New Zephyr user created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        400:
          description: BAD REQUEST – invalid input
          content:
            text/plain:
              schema:
                type: string
                example: Invalid User Registration Request
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Endpoint allowing users to login to Zephyr
      requestBody:
        description: Information required to valid a user during the login process
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        200:
          description: Zephyr user details found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        401:
          description: UNAUTHORIZED - user details not found
          content:
            text/plain:
              schema:
                type: string
                example: Invalid username or password
  # TAG PATHS
  /tags:
    post:
      tags:
        - Tags
      summary: Endpoint for creating new Tags
      requestBody:
        description: Information needed to create a new Tag object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TagRequest"
      responses:
        201:
          description: Newly created Tag object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagResponse"
        400:
          description: BAD REQUEST – invalid input
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Tag Request
    get:
      tags:
        - Tags
      summary: Endpoint for retrieving all Tags
      responses:
        200:
          description: Returns a list of all tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TagResponse"
  /tags/{tagId}:
    get:
      tags:
        - Tags
      summary: Endpoint for retrieving a Tag by ID
      parameters:
        - name: tagId
          in: path
          description: The ID of the Tag
          required: true
          schema:
            type: number
      responses:
        200:
          description: Tag details found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagResponse"
        400:
          description: BAD REQUEST – invalid input
          content:
            text/plain:
              schema:
                type: string
                example: Path parameter 'tagId' missing in request
        404:
          description: NOT FOUND - Tag not found
          content:
            text/plain:
              schema:
                type: string
                example: Tag not found
    put:
      tags:
        - Tags
      summary: Endpoint for updating an existing Tag
      parameters:
        - name: tagId
          in: path
          description: ID of the Tag being updated
          required: true
          schema:
            type: number
      responses:
        200:
          description: Returns the updated Tag details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagResponse"
        400:
          description: BAD REQUEST - invalid input
          content:
            text/plain:
              schema:
                type: string
                example: Path parameter 'tagId' missing in request
        404:
          description: NOT FOUND - Tag not found
          content:
            text/plain:
              schema:
                type: string
                example: Tag not found
    delete:
      tags:
        - Tags
      summary: Endpoint for deleting a Tag via its ID
      parameters:
        - name: tagId
          in: path
          description: ID of the Tag being deleted
          required: true
          schema:
            type: number
      responses:
        200:
          description: OK - Tag deleted
          content:
            text/plain:
              schema:
                type: string
                example: Tag successfully deleted
        404:
          description: NOT FOUND - Tag not found
          content:
            text/plain:
              schema:
                type: string
                example: Tag not found
  /users/{userId}:
    get:
      tags:
        - Users
      summary: Endpoint for retrieving a user by ID
      parameters:
        - name: userId
          in: path
          description: ID of the user being fetch
          required: true
          schema:
            type: number
      responses:
        200:
          description: OK - returns the found user entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetailsResponse"
        404:
          description: NOT FOUND - User not found
          content:
            text/plain:
              schema:
                type: string
                example: User not found
    put:
      tags:
        - Users
      summary: Endpoint for updating a user via ID
      parameters:
        - name: userId
          in: path
          description: ID for the user being updated
          required: true
          schema:
            type: number
      requestBody:
        description: Updated fields to the user entity
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateRequest"
      responses:
        200:
          description: OK - returns the updated user entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetailsResponse"
        404:
          description: NOT FOUND - User not found
          content:
            text/plain:
              schema:
                type: string
                example: User not found
    delete:
      tags:
        - Users
      summary: Endpoint for deleting a user by ID
      parameters:
        - name: userId
          in: path
          description: ID of the user being deleted
          required: true
          schema:
            type: number
      responses:
        200:
          description: OK - User deleted
          content:
            text/plain:
              schema:
                type: string
                example: User successfully deleted
        404:
          description: NOT FOUND - User not found
          content:
            text/plain:
              schema:
                type: string
                example: User not found
  # JOURNAL PATHS
  /journals:
    post:
      tags:
        - Journals
      summary: Endpoint for creating new journal
      requestBody:
        description: Data required to create new Journal object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JournalRequest"
      responses:
        201:
          description: The created journal object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JournalResponse"
        400:
          description: BAD REQUEST - Invalid journal data
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Journal Request
  /journals/{journalId}:
    get:
      tags:
        - Journals
      summary: Endpoint for requesting a journal by ID
      parameters:
        - name: journalId
          in: path
          description: ID of the journal being requested
          required: true
          schema:
            type: number
      responses:
        200:
          description: The journal associated with the provided ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JournalResponse"
        400:
          description: BAD REQUEST - invalid input
          content:
            text/plain:
              schema:
                type: string
                example: Path parameter 'journalId' missing in request
        404:
          description: NOT FOUND - Journal not found
          content:
            text/plain:
              schema:
                type: string
                example: Journal Not Found
    put:
      tags:
        - Journals
      summary: Endpoint for updating a journal with a given ID
      parameters:
        - name: journalId
          in: path
          description: ID of the journal being updated
          required: true
          schema:
            type: number
      responses:
        200:
          description: The updated journal associated with the provided ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JournalResponse"
        400:
          description: BAD REQUEST - invalid input
          content:
            text/plain:
              schema:
                type: string
                example: Path parameter 'journalId' missing in request
        404:
          description: NOT FOUND - Journal being updated was not found
          content:
            text/plain:
              schema:
                type: string
                example: Journal Not Found
    delete:
      tags:
        - Journals
      summary: Endpoint for deleting a journal with a given ID
      parameters:
        - name: journalId
          in: path
          description: ID of the journal being deleted
          required: true
          schema:
            type: number
      responses:
        200:
          description: OK - Journal deleted
          content:
            text/plain:
              schema:
                type: string
                example: Journal Successfully deleted
        404:
          description: NOT FOUND - Journal not found
          content:
            text/plain:
              schema:
                type: string
                example: Journal Not Found



components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - firstName
        - lastName
        - dateOfBirth
        - username
        - email
        - password

    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    UserResponse:
      type: object
      properties:
        id:
          type: number
          example: 1
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        username:
          type: string
          example: JohnDoe123
      required:
        - id
        - firstName
        - lastName
        - username

    AuthResponse:
      type: object
      properties:
        token:
          type: string
          example: "jwt12345"
        user:
          $ref: "#/components/schemas/UserResponse"
      required:
        - token
        - user

    TagRequest:
      type: object
      properties:
        name:
          type: string
        hexColor:
          type: string
      required:
        - name
        - hexColor

    TagResponse:
      type: object
      properties:
        id:
          type: number
          example: 10
        name:
          type: string
          example: "red"
        hexColor:
          type: string
          example: "#FF0000"
      required:
        - id
        - name
        - hexColor

    UserUpdateRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        gender:
          type: string
        phoneNumber:
          type: string
        countryCode:
          type: string

    UserDetailsResponse:
      type: object
      properties:
        id:
          type: number
          example: 139
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        dateOfBirth:
          type: string
          example: 1991-01-01
        gender:
          type: string
          example: MALE
        username:
          type: string
          example: JohnDoe123
        email:
          type: string
          example: john.doe@mail.com
        phoneNumber:
          type: string
          example: 073456789102
        createdAt:
          type: string
          example: 2025-11-28T14:27:56.293437
        updatedAt:
          type: string
          example: 2025-11-30T16:28:51.849528
      required:
        - id
        - firstName
        - lastName
        - dateOfBirth
        - gender
        - username
        - email
        - createdAt

    JournalRequest:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content

    JournalResponse:
      type: object
      properties:
        id:
          type: number
          example: 50
        title:
          type: string
          example: Journal Title
        content:
          type: string
          example: This is the content for my first journal
        createdAt:
          type: string
          example: 2025-12-02T18:56:26.999057
        updatedAt:
          type: string
          example: 2025-12-02T18:58:15.529160
        updateCount:
          type: number
          example: 1
      required:
        - id
        - title
        - content
        - createdAt
        - updateCount
