openapi: "3.0.3"

info:
  title: "Zephyr API"
  description: "This API allows authenticated users to create, edit, and manage journals"
  version: "0.0.1"

servers:
  - url: "http://0.0.0.0:8080"
    description: Development Server

paths:
  # AUTH PATHS
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Endpoint allowing users to register for Zephyr
      requestBody:
        description: Information used to create new user entity
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        201:
          description: New Zephyr user created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        400:
          description: BAD REQUEST – invalid input
          content:
            text/plain:
              schema:
                type: string
                example: Invalid User Registration Request
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Endpoint allowing users to login to Zephyr
      requestBody:
        description: Information required to valid a user during the login process
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        200:
          description: Zephyr user details found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        401:
          description: UNAUTHORIZED - user details not found
          content:
            text/plain:
              schema:
                type: string
                example: Invalid username or password
  # TAG PATHS
  /tags:
    post:
      tags:
        - Tags
      summary: Endpoint for creating new Tags
      requestBody:
        description: Information needed to create a new Tag object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TagRequest"
      responses:
        201:
          description: Newly created Tag object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagResponse"
        400:
          description: BAD REQUEST – invalid input
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Tag Request
    get:
      tags:
        - Tags
      summary: Endpoint for retrieving all Tags
      responses:
        200:
          description: Returns a list of all tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TagResponse"
  /tags/{tagId}:
    get:
      tags:
        - Tags
      summary: Endpoint for retrieving a Tag by ID
      parameters:
        - name: tagId
          in: path
          description: The ID of the Tag
          required: true
          schema:
            type: number
      responses:
        200:
          description: Tag details found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagResponse"
        400:
          description: BAD REQUEST – invalid input
          content:
            text/plain:
              schema:
                type: string
                example: Path parameter 'tagId' missing in request
        404:
          description: NOT FOUND - Tag not found
          content:
            text/plain:
              schema:
                type: string
                example: Tag not found
    put:
      tags:
        - Tags
      summary: Endpoint for updating an existing Tag
      parameters:
        - name: tagId
          in: path
          description: ID of the Tag being updated
          required: true
          schema:
            type: number
      responses:
        200:
          description: Returns the updated Tag details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagResponse"
        400:
          description: BAD REQUEST - invalid input
          content:
            text/plain:
              schema:
                type: string
                example: Path parameter 'tagId' missing in request
        404:
          description: NOT FOUND - Tag not found
          content:
            text/plain:
              schema:
                type: string
                example: Tag not found

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - firstName
        - lastName
        - dateOfBirth
        - username
        - email
        - password

    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    UserResponse:
      type: object
      properties:
        id:
          type: number
          example: 1
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        username:
          type: string
          example: JohnDoe123
      required:
        - id
        - firstName
        - lastName
        - username

    AuthResponse:
      type: object
      properties:
        token:
          type: string
          example: "jwt12345"
        user:
          $ref: "#/components/schemas/UserResponse"
      required:
        - token
        - user

    TagRequest:
      type: object
      properties:
        name:
          type: string
        hexColor:
          type: string
      required:
        - name
        - hexColor

    TagResponse:
      type: object
      properties:
        id:
          type: number
          example: 10
        name:
          type: string
          example: "red"
        hexColor:
          type: string
          example: "#FF0000"
      required:
        - id
        - name
        - hexColor
